/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 1
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_action = 1,
  anon_sym_apiNamespace = 2,
  anon_sym_api = 3,
  anon_sym_app = 4,
  anon_sym_entity = 5,
  anon_sym_job = 6,
  anon_sym_page = 7,
  anon_sym_query = 8,
  anon_sym_route = 9,
  anon_sym_crud = 10,
  anon_sym_LBRACE = 11,
  anon_sym_COMMA = 12,
  anon_sym_RBRACE = 13,
  anon_sym_COLON = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  sym_identifier = 17,
  sym_string = 18,
  sym_number = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  anon_sym_EmailAndPassword = 22,
  anon_sym_PostgreSQL = 23,
  anon_sym_SQLite = 24,
  anon_sym_Simple = 25,
  anon_sym_PgBoss = 26,
  anon_sym_SMTP = 27,
  anon_sym_SendGrid = 28,
  anon_sym_Mailgun = 29,
  anon_sym_Dummy = 30,
  anon_sym_import = 31,
  anon_sym_from = 32,
  anon_sym_LBRACE_EQpsl = 33,
  anon_sym_psl_EQ_RBRACE = 34,
  anon_sym_LBRACE_EQjson = 35,
  anon_sym_json_EQ_RBRACE = 36,
  sym__closure_text = 37,
  anon_sym_SLASH_SLASH = 38,
  aux_sym_comment_token1 = 39,
  anon_sym_SLASH_STAR = 40,
  aux_sym_comment_token2 = 41,
  anon_sym_SLASH = 42,
  sym_source_file = 43,
  sym_declaration = 44,
  sym_declaration_type = 45,
  sym_declaration_body = 46,
  sym_dict = 47,
  sym_dict_pair = 48,
  sym_array = 49,
  sym_value = 50,
  sym_boolean = 51,
  sym_enum_value = 52,
  sym_js_import = 53,
  sym_prisma_closure = 54,
  sym_json_closure = 55,
  sym_comment = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_dict_repeat1 = 58,
  aux_sym_array_repeat1 = 59,
  alias_sym_json_content = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_action] = "action",
  [anon_sym_apiNamespace] = "apiNamespace",
  [anon_sym_api] = "api",
  [anon_sym_app] = "app",
  [anon_sym_entity] = "entity",
  [anon_sym_job] = "job",
  [anon_sym_page] = "page",
  [anon_sym_query] = "query",
  [anon_sym_route] = "route",
  [anon_sym_crud] = "crud",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_EmailAndPassword] = "EmailAndPassword",
  [anon_sym_PostgreSQL] = "PostgreSQL",
  [anon_sym_SQLite] = "SQLite",
  [anon_sym_Simple] = "Simple",
  [anon_sym_PgBoss] = "PgBoss",
  [anon_sym_SMTP] = "SMTP",
  [anon_sym_SendGrid] = "SendGrid",
  [anon_sym_Mailgun] = "Mailgun",
  [anon_sym_Dummy] = "Dummy",
  [anon_sym_import] = "import",
  [anon_sym_from] = "from",
  [anon_sym_LBRACE_EQpsl] = "{=psl",
  [anon_sym_psl_EQ_RBRACE] = "psl=}",
  [anon_sym_LBRACE_EQjson] = "{=json",
  [anon_sym_json_EQ_RBRACE] = "json=}",
  [sym__closure_text] = "prisma_content",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_declaration_type] = "declaration_type",
  [sym_declaration_body] = "declaration_body",
  [sym_dict] = "dict",
  [sym_dict_pair] = "dict_pair",
  [sym_array] = "array",
  [sym_value] = "value",
  [sym_boolean] = "boolean",
  [sym_enum_value] = "enum_value",
  [sym_js_import] = "js_import",
  [sym_prisma_closure] = "prisma_closure",
  [sym_json_closure] = "json_closure",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_dict_repeat1] = "dict_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [alias_sym_json_content] = "json_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_action] = anon_sym_action,
  [anon_sym_apiNamespace] = anon_sym_apiNamespace,
  [anon_sym_api] = anon_sym_api,
  [anon_sym_app] = anon_sym_app,
  [anon_sym_entity] = anon_sym_entity,
  [anon_sym_job] = anon_sym_job,
  [anon_sym_page] = anon_sym_page,
  [anon_sym_query] = anon_sym_query,
  [anon_sym_route] = anon_sym_route,
  [anon_sym_crud] = anon_sym_crud,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_EmailAndPassword] = anon_sym_EmailAndPassword,
  [anon_sym_PostgreSQL] = anon_sym_PostgreSQL,
  [anon_sym_SQLite] = anon_sym_SQLite,
  [anon_sym_Simple] = anon_sym_Simple,
  [anon_sym_PgBoss] = anon_sym_PgBoss,
  [anon_sym_SMTP] = anon_sym_SMTP,
  [anon_sym_SendGrid] = anon_sym_SendGrid,
  [anon_sym_Mailgun] = anon_sym_Mailgun,
  [anon_sym_Dummy] = anon_sym_Dummy,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_LBRACE_EQpsl] = anon_sym_LBRACE_EQpsl,
  [anon_sym_psl_EQ_RBRACE] = anon_sym_psl_EQ_RBRACE,
  [anon_sym_LBRACE_EQjson] = anon_sym_LBRACE_EQjson,
  [anon_sym_json_EQ_RBRACE] = anon_sym_json_EQ_RBRACE,
  [sym__closure_text] = sym__closure_text,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_declaration_type] = sym_declaration_type,
  [sym_declaration_body] = sym_declaration_body,
  [sym_dict] = sym_dict,
  [sym_dict_pair] = sym_dict_pair,
  [sym_array] = sym_array,
  [sym_value] = sym_value,
  [sym_boolean] = sym_boolean,
  [sym_enum_value] = sym_enum_value,
  [sym_js_import] = sym_js_import,
  [sym_prisma_closure] = sym_prisma_closure,
  [sym_json_closure] = sym_json_closure,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_dict_repeat1] = aux_sym_dict_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [alias_sym_json_content] = alias_sym_json_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_action] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_apiNamespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_api] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_app] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_job] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_page] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_query] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_route] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_crud] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EmailAndPassword] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PostgreSQL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQLite] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Simple] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PgBoss] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SMTP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SendGrid] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Mailgun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Dummy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_EQpsl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_psl_EQ_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_EQjson] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_json_EQ_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__closure_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_type] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_body] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym_dict_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_value] = {
    .visible = true,
    .named = true,
  },
  [sym_js_import] = {
    .visible = true,
    .named = true,
  },
  [sym_prisma_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_json_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dict_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_json_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_json_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(129);
      ADVANCE_MAP(
        '"', 2,
        ',', 142,
        '/', 270,
        ':', 144,
        'D', 117,
        'E', 72,
        'M', 23,
        'P', 48,
        'S', 17,
        '[', 145,
        ']', 146,
        'a', 31,
        'c', 93,
        'e', 78,
        'f', 24,
        'i', 66,
        'j', 80,
        'p', 25,
        'q', 115,
        'r', 83,
        't', 95,
        '{', 141,
        '}', 143,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '/', 3,
        'D', 211,
        'E', 186,
        'M', 158,
        'P', 171,
        'S', 152,
        '[', 145,
        ']', 146,
        'f', 159,
        'i', 182,
        't', 195,
        '{', 141,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(215);
      if (lookahead == '\\') ADVANCE(128);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(266);
      if (lookahead == '/') ADVANCE(260);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(269);
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(269);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(267);
      if (lookahead == '/') ADVANCE(261);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '{') ADVANCE(140);
      if (lookahead == '}') ADVANCE(143);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(247);
      if (lookahead == 'j') ADVANCE(255);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(248);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(247);
      if (lookahead == 'p') ADVANCE(256);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(249);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(125);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(126);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(77);
      END_STATE();
    case 13:
      if (lookahead == 'B') ADVANCE(86);
      END_STATE();
    case 14:
      if (lookahead == 'G') ADVANCE(94);
      END_STATE();
    case 15:
      if (lookahead == 'L') ADVANCE(224);
      END_STATE();
    case 16:
      if (lookahead == 'L') ADVANCE(58);
      END_STATE();
    case 17:
      if (lookahead == 'M') ADVANCE(22);
      if (lookahead == 'Q') ADVANCE(16);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 18:
      if (lookahead == 'P') ADVANCE(232);
      END_STATE();
    case 19:
      if (lookahead == 'P') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'Q') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'S') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'T') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead == 'r') ADVANCE(87);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(49);
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(55);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(107);
      END_STATE();
    case 30:
      if (lookahead == 'b') ADVANCE(135);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(109);
      if (lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 33:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 34:
      if (lookahead == 'd') ADVANCE(139);
      END_STATE();
    case 35:
      if (lookahead == 'd') ADVANCE(234);
      END_STATE();
    case 36:
      if (lookahead == 'd') ADVANCE(222);
      END_STATE();
    case 37:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(136);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(218);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(220);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(138);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(226);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(228);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(131);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 48:
      if (lookahead == 'g') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 49:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 50:
      if (lookahead == 'g') ADVANCE(98);
      END_STATE();
    case 51:
      if (lookahead == 'g') ADVANCE(120);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(132);
      if (lookahead == 'p') ADVANCE(133);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(111);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 56:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(84);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(113);
      END_STATE();
    case 59:
      if (lookahead == 'j') ADVANCE(106);
      if (lookahead == 'p') ADVANCE(105);
      END_STATE();
    case 60:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 61:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 62:
      if (lookahead == 'l') ADVANCE(243);
      END_STATE();
    case 63:
      if (lookahead == 'l') ADVANCE(103);
      END_STATE();
    case 64:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 66:
      if (lookahead == 'm') ADVANCE(90);
      END_STATE();
    case 67:
      if (lookahead == 'm') ADVANCE(122);
      END_STATE();
    case 68:
      if (lookahead == 'm') ADVANCE(242);
      END_STATE();
    case 69:
      if (lookahead == 'm') ADVANCE(91);
      END_STATE();
    case 70:
      if (lookahead == 'm') ADVANCE(67);
      END_STATE();
    case 71:
      if (lookahead == 'm') ADVANCE(47);
      END_STATE();
    case 72:
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 73:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 74:
      if (lookahead == 'n') ADVANCE(130);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(245);
      END_STATE();
    case 76:
      if (lookahead == 'n') ADVANCE(236);
      END_STATE();
    case 77:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(114);
      END_STATE();
    case 79:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 80:
      if (lookahead == 'o') ADVANCE(30);
      if (lookahead == 's') ADVANCE(82);
      END_STATE();
    case 81:
      if (lookahead == 'o') ADVANCE(96);
      END_STATE();
    case 82:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 83:
      if (lookahead == 'o') ADVANCE(118);
      END_STATE();
    case 84:
      if (lookahead == 'o') ADVANCE(74);
      END_STATE();
    case 85:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 86:
      if (lookahead == 'o') ADVANCE(104);
      END_STATE();
    case 87:
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 88:
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 89:
      if (lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 90:
      if (lookahead == 'p') ADVANCE(81);
      END_STATE();
    case 91:
      if (lookahead == 'p') ADVANCE(65);
      END_STATE();
    case 92:
      if (lookahead == 'r') ADVANCE(123);
      END_STATE();
    case 93:
      if (lookahead == 'r') ADVANCE(116);
      END_STATE();
    case 94:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 95:
      if (lookahead == 'r') ADVANCE(119);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(108);
      END_STATE();
    case 97:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 98:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 99:
      if (lookahead == 's') ADVANCE(230);
      END_STATE();
    case 100:
      if (lookahead == 's') ADVANCE(121);
      END_STATE();
    case 101:
      if (lookahead == 's') ADVANCE(110);
      END_STATE();
    case 102:
      if (lookahead == 's') ADVANCE(89);
      END_STATE();
    case 103:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 104:
      if (lookahead == 's') ADVANCE(99);
      END_STATE();
    case 105:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 106:
      if (lookahead == 's') ADVANCE(85);
      END_STATE();
    case 107:
      if (lookahead == 's') ADVANCE(100);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(240);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 110:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 111:
      if (lookahead == 't') ADVANCE(124);
      END_STATE();
    case 112:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 113:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 114:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 115:
      if (lookahead == 'u') ADVANCE(46);
      END_STATE();
    case 116:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 117:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 118:
      if (lookahead == 'u') ADVANCE(112);
      END_STATE();
    case 119:
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 120:
      if (lookahead == 'u') ADVANCE(76);
      END_STATE();
    case 121:
      if (lookahead == 'w') ADVANCE(88);
      END_STATE();
    case 122:
      if (lookahead == 'y') ADVANCE(238);
      END_STATE();
    case 123:
      if (lookahead == 'y') ADVANCE(137);
      END_STATE();
    case 124:
      if (lookahead == 'y') ADVANCE(134);
      END_STATE();
    case 125:
      if (lookahead == '}') ADVANCE(244);
      END_STATE();
    case 126:
      if (lookahead == '}') ADVANCE(246);
      END_STATE();
    case 127:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(217);
      END_STATE();
    case 128:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_action);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_apiNamespace);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_api);
      if (lookahead == 'N') ADVANCE(27);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_app);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_entity);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_job);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_page);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_query);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_route);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_crud);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(189);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'B') ADVANCE(191);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'G') ADVANCE(196);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(225);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L') ADVANCE(175);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M') ADVANCE(157);
      if (lookahead == 'Q') ADVANCE(151);
      if (lookahead == 'e') ADVANCE(187);
      if (lookahead == 'i') ADVANCE(184);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(233);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'Q') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(155);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(153);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(180);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(205);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(235);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(223);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(154);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(219);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(221);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(227);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(229);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(156);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(148);
      if (lookahead == 'o') ADVANCE(200);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(210);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(199);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(178);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(208);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(179);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(163);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(172);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(147);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(203);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(169);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(193);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(213);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(194);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(183);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(160);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(162);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(237);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(197);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(204);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(198);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(190);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(181);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(209);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(206);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(170);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(207);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(231);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(212);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(167);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(201);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(202);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(241);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(173);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(168);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(188);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(185);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(192);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(239);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(217);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(anon_sym_EmailAndPassword);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(anon_sym_EmailAndPassword);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(anon_sym_PostgreSQL);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(anon_sym_PostgreSQL);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(anon_sym_SQLite);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(anon_sym_SQLite);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(anon_sym_Simple);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(anon_sym_Simple);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(anon_sym_PgBoss);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(anon_sym_PgBoss);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(anon_sym_SMTP);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(anon_sym_SMTP);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(anon_sym_SendGrid);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(anon_sym_SendGrid);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(anon_sym_Mailgun);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(anon_sym_Mailgun);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(anon_sym_Dummy);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(anon_sym_Dummy);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(anon_sym_import);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(214);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(anon_sym_LBRACE_EQpsl);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(anon_sym_psl_EQ_RBRACE);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(anon_sym_LBRACE_EQjson);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(anon_sym_json_EQ_RBRACE);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == '*') ADVANCE(266);
      if (lookahead == '/') ADVANCE(260);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == '/') ADVANCE(247);
      if (lookahead == 'j') ADVANCE(255);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(248);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == '/') ADVANCE(247);
      if (lookahead == 'p') ADVANCE(256);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(249);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == '=') ADVANCE(258);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == '=') ADVANCE(257);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == 'l') ADVANCE(251);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == 'n') ADVANCE(250);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == 'o') ADVANCE(253);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == 's') ADVANCE(254);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == 's') ADVANCE(252);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == '}') ADVANCE(244);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 258:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead == '}') ADVANCE(246);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 259:
      ACCEPT_TOKEN(sym__closure_text);
      if (lookahead != 0) ADVANCE(259);
      END_STATE();
    case 260:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 261:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(269);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 262:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(265);
      END_STATE();
    case 263:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(268);
      if (lookahead == '/') ADVANCE(262);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(265);
      END_STATE();
    case 264:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(263);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(264);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(265);
      END_STATE();
    case 265:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(265);
      END_STATE();
    case 266:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 267:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(269);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 268:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(265);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(269);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(266);
      if (lookahead == '/') ADVANCE(260);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 264},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 7},
  [61] = {(TSStateId)(-1),},
  [62] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_action] = ACTIONS(1),
    [anon_sym_apiNamespace] = ACTIONS(1),
    [anon_sym_api] = ACTIONS(1),
    [anon_sym_app] = ACTIONS(1),
    [anon_sym_entity] = ACTIONS(1),
    [anon_sym_job] = ACTIONS(1),
    [anon_sym_page] = ACTIONS(1),
    [anon_sym_query] = ACTIONS(1),
    [anon_sym_route] = ACTIONS(1),
    [anon_sym_crud] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_EmailAndPassword] = ACTIONS(1),
    [anon_sym_PostgreSQL] = ACTIONS(1),
    [anon_sym_SQLite] = ACTIONS(1),
    [anon_sym_Simple] = ACTIONS(1),
    [anon_sym_PgBoss] = ACTIONS(1),
    [anon_sym_SMTP] = ACTIONS(1),
    [anon_sym_SendGrid] = ACTIONS(1),
    [anon_sym_Mailgun] = ACTIONS(1),
    [anon_sym_Dummy] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_LBRACE_EQpsl] = ACTIONS(1),
    [anon_sym_psl_EQ_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_EQjson] = ACTIONS(1),
    [anon_sym_json_EQ_RBRACE] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(48),
    [sym_declaration] = STATE(18),
    [sym_declaration_type] = STATE(58),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_action] = ACTIONS(9),
    [anon_sym_apiNamespace] = ACTIONS(9),
    [anon_sym_api] = ACTIONS(11),
    [anon_sym_app] = ACTIONS(9),
    [anon_sym_entity] = ACTIONS(9),
    [anon_sym_job] = ACTIONS(9),
    [anon_sym_page] = ACTIONS(9),
    [anon_sym_query] = ACTIONS(9),
    [anon_sym_route] = ACTIONS(9),
    [anon_sym_crud] = ACTIONS(9),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_dict] = STATE(26),
    [sym_array] = STATE(26),
    [sym_value] = STATE(32),
    [sym_boolean] = STATE(26),
    [sym_enum_value] = STATE(26),
    [sym_js_import] = STATE(26),
    [sym_prisma_closure] = STATE(26),
    [sym_json_closure] = STATE(26),
    [sym_comment] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_EmailAndPassword] = ACTIONS(25),
    [anon_sym_PostgreSQL] = ACTIONS(25),
    [anon_sym_SQLite] = ACTIONS(25),
    [anon_sym_Simple] = ACTIONS(25),
    [anon_sym_PgBoss] = ACTIONS(25),
    [anon_sym_SMTP] = ACTIONS(25),
    [anon_sym_SendGrid] = ACTIONS(25),
    [anon_sym_Mailgun] = ACTIONS(25),
    [anon_sym_Dummy] = ACTIONS(25),
    [anon_sym_import] = ACTIONS(27),
    [anon_sym_LBRACE_EQpsl] = ACTIONS(29),
    [anon_sym_LBRACE_EQjson] = ACTIONS(31),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym_dict] = STATE(26),
    [sym_array] = STATE(26),
    [sym_value] = STATE(44),
    [sym_boolean] = STATE(26),
    [sym_enum_value] = STATE(26),
    [sym_js_import] = STATE(26),
    [sym_prisma_closure] = STATE(26),
    [sym_json_closure] = STATE(26),
    [sym_comment] = STATE(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(33),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_EmailAndPassword] = ACTIONS(25),
    [anon_sym_PostgreSQL] = ACTIONS(25),
    [anon_sym_SQLite] = ACTIONS(25),
    [anon_sym_Simple] = ACTIONS(25),
    [anon_sym_PgBoss] = ACTIONS(25),
    [anon_sym_SMTP] = ACTIONS(25),
    [anon_sym_SendGrid] = ACTIONS(25),
    [anon_sym_Mailgun] = ACTIONS(25),
    [anon_sym_Dummy] = ACTIONS(25),
    [anon_sym_import] = ACTIONS(27),
    [anon_sym_LBRACE_EQpsl] = ACTIONS(29),
    [anon_sym_LBRACE_EQjson] = ACTIONS(31),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [STATE(4)] = {
    [sym_dict] = STATE(26),
    [sym_array] = STATE(26),
    [sym_value] = STATE(44),
    [sym_boolean] = STATE(26),
    [sym_enum_value] = STATE(26),
    [sym_js_import] = STATE(26),
    [sym_prisma_closure] = STATE(26),
    [sym_json_closure] = STATE(26),
    [sym_comment] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(35),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_EmailAndPassword] = ACTIONS(25),
    [anon_sym_PostgreSQL] = ACTIONS(25),
    [anon_sym_SQLite] = ACTIONS(25),
    [anon_sym_Simple] = ACTIONS(25),
    [anon_sym_PgBoss] = ACTIONS(25),
    [anon_sym_SMTP] = ACTIONS(25),
    [anon_sym_SendGrid] = ACTIONS(25),
    [anon_sym_Mailgun] = ACTIONS(25),
    [anon_sym_Dummy] = ACTIONS(25),
    [anon_sym_import] = ACTIONS(27),
    [anon_sym_LBRACE_EQpsl] = ACTIONS(29),
    [anon_sym_LBRACE_EQjson] = ACTIONS(31),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_import,
    ACTIONS(29), 1,
      anon_sym_LBRACE_EQpsl,
    ACTIONS(31), 1,
      anon_sym_LBRACE_EQjson,
    STATE(5), 1,
      sym_comment,
    STATE(41), 1,
      sym_value,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 7,
      sym_dict,
      sym_array,
      sym_boolean,
      sym_enum_value,
      sym_js_import,
      sym_prisma_closure,
      sym_json_closure,
    ACTIONS(25), 9,
      anon_sym_EmailAndPassword,
      anon_sym_PostgreSQL,
      anon_sym_SQLite,
      anon_sym_Simple,
      anon_sym_PgBoss,
      anon_sym_SMTP,
      anon_sym_SendGrid,
      anon_sym_Mailgun,
      anon_sym_Dummy,
  [59] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_import,
    ACTIONS(29), 1,
      anon_sym_LBRACE_EQpsl,
    ACTIONS(31), 1,
      anon_sym_LBRACE_EQjson,
    STATE(6), 1,
      sym_comment,
    STATE(44), 1,
      sym_value,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 7,
      sym_dict,
      sym_array,
      sym_boolean,
      sym_enum_value,
      sym_js_import,
      sym_prisma_closure,
      sym_json_closure,
    ACTIONS(25), 9,
      anon_sym_EmailAndPassword,
      anon_sym_PostgreSQL,
      anon_sym_SQLite,
      anon_sym_Simple,
      anon_sym_PgBoss,
      anon_sym_SMTP,
      anon_sym_SendGrid,
      anon_sym_Mailgun,
      anon_sym_Dummy,
  [118] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(39), 1,
      anon_sym_api,
    STATE(7), 1,
      sym_comment,
    ACTIONS(37), 13,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [146] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_api,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(18), 1,
      sym_declaration,
    STATE(58), 1,
      sym_declaration_type,
    ACTIONS(9), 9,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
  [182] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(45), 1,
      anon_sym_api,
    STATE(9), 1,
      sym_comment,
    ACTIONS(43), 13,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [210] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      anon_sym_api,
    STATE(18), 1,
      sym_declaration,
    STATE(58), 1,
      sym_declaration_type,
    STATE(10), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    ACTIONS(49), 9,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
  [244] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(57), 1,
      anon_sym_api,
    STATE(11), 1,
      sym_comment,
    ACTIONS(55), 13,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [272] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(61), 1,
      anon_sym_api,
    STATE(12), 1,
      sym_comment,
    ACTIONS(59), 13,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [300] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(65), 1,
      anon_sym_api,
    STATE(13), 1,
      sym_comment,
    ACTIONS(63), 13,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [328] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(69), 1,
      anon_sym_api,
    STATE(14), 1,
      sym_comment,
    ACTIONS(67), 13,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [356] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(73), 1,
      anon_sym_api,
    STATE(15), 1,
      sym_comment,
    ACTIONS(71), 13,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [384] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(77), 1,
      anon_sym_api,
    STATE(16), 1,
      sym_comment,
    ACTIONS(75), 13,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [412] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(81), 1,
      anon_sym_api,
    STATE(17), 1,
      sym_comment,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
  [437] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(85), 1,
      anon_sym_api,
    STATE(18), 1,
      sym_comment,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
  [462] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(89), 1,
      anon_sym_api,
    STATE(19), 1,
      sym_comment,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_action,
      anon_sym_apiNamespace,
      anon_sym_app,
      anon_sym_entity,
      anon_sym_job,
      anon_sym_page,
      anon_sym_query,
      anon_sym_route,
      anon_sym_crud,
  [487] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_LBRACE_EQpsl,
    ACTIONS(31), 1,
      anon_sym_LBRACE_EQjson,
    STATE(17), 1,
      sym_declaration_body,
    STATE(20), 1,
      sym_comment,
    STATE(19), 3,
      sym_dict,
      sym_prisma_closure,
      sym_json_closure,
  [514] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      sym_comment,
    STATE(36), 1,
      aux_sym_array_repeat1,
  [533] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(93), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [548] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      sym_comment,
    STATE(30), 1,
      aux_sym_dict_repeat1,
  [567] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(24), 1,
      sym_comment,
    STATE(42), 1,
      sym_dict_pair,
  [586] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(101), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [601] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(103), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [616] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [631] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_comment,
    STATE(35), 1,
      sym_dict_pair,
  [650] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      sym_comment,
    STATE(42), 1,
      sym_dict_pair,
  [669] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_COMMA,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_comment,
      aux_sym_dict_repeat1,
  [686] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(116), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [701] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RBRACK,
    STATE(21), 1,
      aux_sym_array_repeat1,
    STATE(32), 1,
      sym_comment,
  [720] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(122), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [735] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(124), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [750] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_dict_repeat1,
    STATE(35), 1,
      sym_comment,
  [769] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(133), 1,
      anon_sym_RBRACK,
    STATE(36), 2,
      sym_comment,
      aux_sym_array_repeat1,
  [786] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(135), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [801] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(137), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [816] = 5,
    ACTIONS(139), 1,
      anon_sym_json_EQ_RBRACE,
    ACTIONS(141), 1,
      sym__closure_text,
    ACTIONS(143), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(145), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
  [832] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(147), 1,
      anon_sym_LBRACE,
    ACTIONS(149), 1,
      sym_identifier,
    STATE(40), 1,
      sym_comment,
  [848] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [862] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(42), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [876] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(42), 1,
      sym_dict_pair,
    STATE(43), 1,
      sym_comment,
  [892] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(44), 1,
      sym_comment,
    ACTIONS(133), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [906] = 5,
    ACTIONS(143), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(145), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(153), 1,
      anon_sym_psl_EQ_RBRACE,
    ACTIONS(155), 1,
      sym__closure_text,
    STATE(45), 1,
      sym_comment,
  [922] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(157), 1,
      anon_sym_from,
    STATE(46), 1,
      sym_comment,
  [935] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(159), 1,
      anon_sym_psl_EQ_RBRACE,
    STATE(47), 1,
      sym_comment,
  [948] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    STATE(48), 1,
      sym_comment,
  [961] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(163), 1,
      anon_sym_json_EQ_RBRACE,
    STATE(49), 1,
      sym_comment,
  [974] = 4,
    ACTIONS(143), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(145), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(165), 1,
      aux_sym_comment_token2,
    STATE(50), 1,
      sym_comment,
  [987] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_comment,
  [1000] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(169), 1,
      sym_string,
    STATE(52), 1,
      sym_comment,
  [1013] = 4,
    ACTIONS(143), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(145), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(171), 1,
      aux_sym_comment_token1,
    STATE(53), 1,
      sym_comment,
  [1026] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(173), 1,
      anon_sym_SLASH,
    STATE(54), 1,
      sym_comment,
  [1039] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(175), 1,
      anon_sym_from,
    STATE(55), 1,
      sym_comment,
  [1052] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(56), 1,
      sym_comment,
  [1065] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(179), 1,
      anon_sym_COLON,
    STATE(57), 1,
      sym_comment,
  [1078] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(181), 1,
      sym_identifier,
    STATE(58), 1,
      sym_comment,
  [1091] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(183), 1,
      sym_string,
    STATE(59), 1,
      sym_comment,
  [1104] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(60), 1,
      sym_comment,
  [1117] = 1,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
  [1121] = 1,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 59,
  [SMALL_STATE(7)] = 118,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 182,
  [SMALL_STATE(10)] = 210,
  [SMALL_STATE(11)] = 244,
  [SMALL_STATE(12)] = 272,
  [SMALL_STATE(13)] = 300,
  [SMALL_STATE(14)] = 328,
  [SMALL_STATE(15)] = 356,
  [SMALL_STATE(16)] = 384,
  [SMALL_STATE(17)] = 412,
  [SMALL_STATE(18)] = 437,
  [SMALL_STATE(19)] = 462,
  [SMALL_STATE(20)] = 487,
  [SMALL_STATE(21)] = 514,
  [SMALL_STATE(22)] = 533,
  [SMALL_STATE(23)] = 548,
  [SMALL_STATE(24)] = 567,
  [SMALL_STATE(25)] = 586,
  [SMALL_STATE(26)] = 601,
  [SMALL_STATE(27)] = 616,
  [SMALL_STATE(28)] = 631,
  [SMALL_STATE(29)] = 650,
  [SMALL_STATE(30)] = 669,
  [SMALL_STATE(31)] = 686,
  [SMALL_STATE(32)] = 701,
  [SMALL_STATE(33)] = 720,
  [SMALL_STATE(34)] = 735,
  [SMALL_STATE(35)] = 750,
  [SMALL_STATE(36)] = 769,
  [SMALL_STATE(37)] = 786,
  [SMALL_STATE(38)] = 801,
  [SMALL_STATE(39)] = 816,
  [SMALL_STATE(40)] = 832,
  [SMALL_STATE(41)] = 848,
  [SMALL_STATE(42)] = 862,
  [SMALL_STATE(43)] = 876,
  [SMALL_STATE(44)] = 892,
  [SMALL_STATE(45)] = 906,
  [SMALL_STATE(46)] = 922,
  [SMALL_STATE(47)] = 935,
  [SMALL_STATE(48)] = 948,
  [SMALL_STATE(49)] = 961,
  [SMALL_STATE(50)] = 974,
  [SMALL_STATE(51)] = 987,
  [SMALL_STATE(52)] = 1000,
  [SMALL_STATE(53)] = 1013,
  [SMALL_STATE(54)] = 1026,
  [SMALL_STATE(55)] = 1039,
  [SMALL_STATE(56)] = 1052,
  [SMALL_STATE(57)] = 1065,
  [SMALL_STATE(58)] = 1078,
  [SMALL_STATE(59)] = 1091,
  [SMALL_STATE(60)] = 1104,
  [SMALL_STATE(61)] = 1117,
  [SMALL_STATE(62)] = 1121,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 4, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 4, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_closure, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_closure, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 5, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prisma_closure, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prisma_closure, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_closure, 3, 0, 1),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_closure, 3, 0, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prisma_closure, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prisma_closure, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_body, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_body, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_import, 6, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_value, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_import, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict_pair, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [161] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_type, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wasp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "wasp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
